MiniDeps.later(function()
    MiniDeps.add("tpope/vim-fugitive")

    vim.keymap.set({ "n", "x" }, "<space>cc", ":GpChatToggle popup<CR>", { remap = true, desc = "[C]opilot [C]hat" })
    vim.keymap.set({ "n" }, "<space>ga", ":Gwrite<CR>", { desc = "[G]it [A]dd" })
    vim.keymap.set({ "n" }, "<space>gc", ":Git commit<CR>", { desc = "[G]it [C]ommit" })
    vim.keymap.set({ "n" }, "<space>gsh", ":Git push<CR>", { desc = "[G]it pu[SH]" })
    vim.keymap.set({ "n" }, "<space>gll", ":Git pull<CR>", { desc = "[G]it pu[LL]" })
    vim.keymap.set({ "n" }, "<space>gg", ":Git<CR>", { desc = "[G]it status" })
    vim.keymap.set({ "n" }, "<space>gb", ":Git blame<CR>", { desc = "[G]it [B]lame" })
    vim.keymap.set({ "n" }, "<space>gd", ":Gvdiff<CR>", { desc = "[G]it [D]iff" })
    vim.keymap.set({ "n" }, "<space>gr", ":GRemove<CR>", { desc = "[G]it [R]emove" })
    vim.keymap.set({ "n" }, "<space>o", ":.GBrowse<CR>", { desc = "Git [O]pen" })
end)
